/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package login;

import java.awt.Color;
import login.Main.Usuario;

/**
 *
 * @author JUAN JOSE
 */
public class Pantalla_de_login extends javax.swing.JPanel {

    /**
     * Creates new form Pantalla_de_login
     */
    public Pantalla_de_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pantalla = new javax.swing.JPanel();
        Nombre2 = new javax.swing.JLabel();
        Nombre1 = new javax.swing.JLabel();
        Text_USER = new javax.swing.JTextField();
        options = new javax.swing.JComboBox<>();
        Nombre_2 = new javax.swing.JLabel();
        Nombre3 = new javax.swing.JLabel();
        Usuario1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        CONTRASEÑA = new javax.swing.JPasswordField();
        Contraseña = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pantalla.setBackground(new java.awt.Color(255, 255, 255));
        Pantalla.setForeground(new java.awt.Color(255, 255, 255));
        Pantalla.setMaximumSize(new java.awt.Dimension(880, 470));
        Pantalla.setMinimumSize(new java.awt.Dimension(880, 470));
        Pantalla.setPreferredSize(new java.awt.Dimension(880, 470));
        Pantalla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nombre2.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        Nombre2.setForeground(new java.awt.Color(242, 242, 242));
        Nombre2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre2.setText("SURTICONFITES");
        Pantalla.add(Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 200, 70));

        Nombre1.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        Nombre1.setForeground(new java.awt.Color(242, 242, 242));
        Nombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre1.setText("MINIPRECIO");
        Pantalla.add(Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 150, 70));

        Text_USER.setForeground(new java.awt.Color(204, 204, 204));
        Text_USER.setText("Username");
        Text_USER.setBorder(null);
        Text_USER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Text_USERMousePressed(evt);
            }
        });
        Text_USER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_USERActionPerformed(evt);
            }
        });
        Pantalla.add(Text_USER, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 390, 40));

        options.setBackground(new java.awt.Color(255, 255, 255));
        options.setForeground(new java.awt.Color(0, 0, 0));
        options.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Vendedora", "Bodeguero" }));
        options.setBorder(null);
        options.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsActionPerformed(evt);
            }
        });
        Pantalla.add(options, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        Nombre_2.setForeground(new java.awt.Color(245, 245, 245));
        Nombre_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WhatsApp Image 2024-08-27 at 9.58.55 PM.jpeg"))); // NOI18N
        Nombre_2.setText("HOLAAAAAAAAAAAAAAAAAA");
        Pantalla.add(Nombre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, -50, 340, 610));

        Nombre3.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        Nombre3.setForeground(new java.awt.Color(0, 0, 0));
        Nombre3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre3.setText("INICIAR SESION");
        Pantalla.add(Nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 200, 70));

        Usuario1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Usuario1.setForeground(new java.awt.Color(0, 0, 0));
        Usuario1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Usuario1.setText("USUARIO");
        Usuario1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Usuario1MousePressed(evt);
            }
        });
        Pantalla.add(Usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 100, 200, 70));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        Pantalla.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 390, 50));

        CONTRASEÑA.setForeground(new java.awt.Color(204, 204, 204));
        CONTRASEÑA.setText("*********");
        CONTRASEÑA.setToolTipText("");
        CONTRASEÑA.setBorder(null);
        CONTRASEÑA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CONTRASEÑAMousePressed(evt);
            }
        });
        CONTRASEÑA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONTRASEÑAActionPerformed(evt);
            }
        });
        Pantalla.add(CONTRASEÑA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 400, 40));

        Contraseña.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Contraseña.setForeground(new java.awt.Color(0, 0, 0));
        Contraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Contraseña.setText("CONTRASEÑA");
        Pantalla.add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 200, 70));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        Pantalla.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 400, 50));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENTRAR");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(12, 12, 12))
        );

        Pantalla.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 120, 40));

        add(Pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void Text_USERMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Text_USERMousePressed
        if (Text_USER.getText().equals("Username")){
            Text_USER.setText("");
            Text_USER.setForeground(Color.black);
        }
        if (String.valueOf(CONTRASEÑA.getPassword()).isEmpty()    ){
            CONTRASEÑA.setText("*********");
            CONTRASEÑA.setForeground(Color.gray);
        }
    }//GEN-LAST:event_Text_USERMousePressed

    private void Text_USERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_USERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_USERActionPerformed

    private void optionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optionsActionPerformed

    private void Usuario1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Usuario1MousePressed

    }//GEN-LAST:event_Usuario1MousePressed

    private void CONTRASEÑAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CONTRASEÑAMousePressed
        if (Text_USER.getText().isEmpty()){
            Text_USER.setText("Username");
            Text_USER.setForeground(Color.gray);
        }

        if (String.valueOf(CONTRASEÑA.getPassword()).equals("*********")    ){
            CONTRASEÑA.setText("");// TODO add your handling code here:
            CONTRASEÑA.setForeground(Color.black);
        }

    }//GEN-LAST:event_CONTRASEÑAMousePressed

    private void CONTRASEÑAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONTRASEÑAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CONTRASEÑAActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        String  user = Text_USER.getText();

        for (Usuario usuario :BaseDeDatos.usuarios ){
            if ((Text_USER.getText().equals("Username"))&&(String.valueOf(CONTRASEÑA.getPassword()).equals("*********")) ){
                javax.swing.JOptionPane.showMessageDialog(this,"Porfavor llene los datos");
                break;
            }

            if(usuario.getNombreUsuario().equals(user) && usuario.getCargo().equals(options.getSelectedItem()) && usuario.getContraseña().equals(String.valueOf(CONTRASEÑA.getPassword()))){
                if (usuario.getCargo().equals("Administrador")){
                    Admin admi= new Admin();
                    
                    Main.ShowPanel(admi , Pantalla , 880, 480);

                    break;
                }else{
                    if (usuario.getCargo().equals("Vendedora")){

                        Vend vend= new Vend();
                       
                        Main.ShowPanel(vend, Pantalla, 880, 480);
                        break;
                    }else{

                        Bode bode= new Bode();
                      
                        Main.ShowPanel(bode, Pantalla, 880, 480);
                        break;
                    }
                }

            }
        }
        javax.swing.JOptionPane.showMessageDialog(this,"El usuario o contraseña utilizados no se encuentran registrados");
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CONTRASEÑA;
    private javax.swing.JLabel Contraseña;
    private javax.swing.JLabel Nombre1;
    private javax.swing.JLabel Nombre2;
    private javax.swing.JLabel Nombre3;
    private javax.swing.JLabel Nombre_2;
    private javax.swing.JPanel Pantalla;
    private javax.swing.JTextField Text_USER;
    private javax.swing.JLabel Usuario1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> options;
    // End of variables declaration//GEN-END:variables
}
