/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import java.awt.Color;

/**
 *
 * @author JUAN JOSE
 */
public class Login extends javax.swing.JFrame {
    int Xmouse, Ymouse;
    String   Admin_user,admin_contra,vend_user,vend_contra,bode_user,bode_contra; 
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        LOG.setSize(800,500);
        LOG.setLocation(500,500);
        Admin_user ="admin";
        admin_contra ="123";
        vend_user ="vend";
        vend_contra="123";
        bode_user ="bode";
        bode_contra ="123";
       
         
                
    
   
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LOG = new javax.swing.JPanel();
        Contraseña = new javax.swing.JLabel();
        Nombre1 = new javax.swing.JLabel();
        Nombre2 = new javax.swing.JLabel();
        Nombre_2 = new javax.swing.JLabel();
        CONTRASEÑA = new javax.swing.JPasswordField();
        Nombre3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Usuario1 = new javax.swing.JLabel();
        Text_USER = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Boton_cerrado = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        options = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 204));
        setLocation(new java.awt.Point(225, 225));
        setMaximumSize(new java.awt.Dimension(800, 500));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        LOG.setBackground(new java.awt.Color(255, 255, 255));
        LOG.setForeground(new java.awt.Color(242, 242, 242));
        LOG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Contraseña.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Contraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Contraseña.setText("CONTRASEÑA");
        LOG.add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 200, 70));

        Nombre1.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        Nombre1.setForeground(new java.awt.Color(242, 242, 242));
        Nombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre1.setText("MINIPRECIO");
        LOG.add(Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 150, 70));

        Nombre2.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        Nombre2.setForeground(new java.awt.Color(242, 242, 242));
        Nombre2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre2.setText("SURTICONFITES");
        LOG.add(Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 200, 70));

        Nombre_2.setForeground(new java.awt.Color(245, 245, 245));
        Nombre_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WhatsApp Image 2024-08-27 at 9.58.55 PM.jpeg"))); // NOI18N
        Nombre_2.setText("HOLAAAAAAAAAAAAAAAAAA");
        LOG.add(Nombre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, -60, 340, 610));

        CONTRASEÑA.setForeground(new java.awt.Color(204, 204, 204));
        CONTRASEÑA.setText("*********");
        CONTRASEÑA.setToolTipText("");
        CONTRASEÑA.setBorder(null);
        CONTRASEÑA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CONTRASEÑAMousePressed(evt);
            }
        });
        CONTRASEÑA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONTRASEÑAActionPerformed(evt);
            }
        });
        LOG.add(CONTRASEÑA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 400, 30));

        Nombre3.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        Nombre3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre3.setText("INICIAR SESION");
        LOG.add(Nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 200, 70));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        LOG.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 400, 50));

        Usuario1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Usuario1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Usuario1.setText("USUARIO");
        Usuario1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Usuario1MousePressed(evt);
            }
        });
        LOG.add(Usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 170, 200, 70));

        Text_USER.setForeground(new java.awt.Color(204, 204, 204));
        Text_USER.setText("Username");
        Text_USER.setBorder(null);
        Text_USER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Text_USERMousePressed(evt);
            }
        });
        Text_USER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_USERActionPerformed(evt);
            }
        });
        LOG.add(Text_USER, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 390, 40));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        LOG.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 390, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        Boton_cerrado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Boton_cerrado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Boton_cerrado.setText("X");
        Boton_cerrado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_cerrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_cerradoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton_cerradoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton_cerradoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Boton_cerradoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Boton_cerrado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Boton_cerrado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        LOG.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 880, 60));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENTRAR");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(10, 10, 10))
        );

        LOG.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 120, 40));

        options.setForeground(new java.awt.Color(255, 255, 255));
        options.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Vendedora", "Bodeguero" }));
        options.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsActionPerformed(evt);
            }
        });
        LOG.add(options, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LOG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LOG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Text_USERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_USERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_USERActionPerformed

    private void CONTRASEÑAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONTRASEÑAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CONTRASEÑAActionPerformed

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        Xmouse= evt.getX();
        Ymouse =evt.getY();
                
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-Xmouse, y-Ymouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void Boton_cerradoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_cerradoMousePressed
        
    }//GEN-LAST:event_Boton_cerradoMousePressed

    private void Boton_cerradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_cerradoMouseClicked
        System.exit(0);
    }//GEN-LAST:event_Boton_cerradoMouseClicked

    private void Boton_cerradoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_cerradoMouseEntered
        Boton_cerrado.setBackground( Color.red);
    }//GEN-LAST:event_Boton_cerradoMouseEntered

    private void Boton_cerradoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_cerradoMouseExited
        Boton_cerrado.setBackground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_cerradoMouseExited

    private void Usuario1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Usuario1MousePressed
          
    }//GEN-LAST:event_Usuario1MousePressed

    private void CONTRASEÑAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CONTRASEÑAMousePressed
        if (Text_USER.getText().isEmpty()){
            Text_USER.setText("Username");
            Text_USER.setForeground(Color.gray);
        }
        
        
        if (String.valueOf(CONTRASEÑA.getPassword()).equals("*********")    ){
            CONTRASEÑA.setText("");// TODO add your handling code here:
            CONTRASEÑA.setForeground(Color.black);
        }
        
    }//GEN-LAST:event_CONTRASEÑAMousePressed

    private void Text_USERMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Text_USERMousePressed
        if (Text_USER.getText().equals("Username")){
            Text_USER.setText("");
            Text_USER.setForeground(Color.black);
        }
        if (String.valueOf(CONTRASEÑA.getPassword()).isEmpty()    ){
            CONTRASEÑA.setText("*********");
            CONTRASEÑA.setForeground(Color.gray);
        }
    }//GEN-LAST:event_Text_USERMousePressed

    private void optionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optionsActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
             if (options.getSelectedItem().equals("Administrador")){
                 if ((Text_USER.getText().equals(Admin_user))&&(String.valueOf(CONTRASEÑA.getPassword()).equals(admin_contra)) ){
                     
                     ADMI admi = new ADMI();
                     admi.setSize(800,500);
                     admi.setLocation(225,225);
                     
                     LOG.removeAll();
                     LOG.revalidate();
                     LOG.repaint();
                     
                 }else{
                     
                     if ((Text_USER.getText().equals("Username"))&&(String.valueOf(CONTRASEÑA.getPassword()).equals("*********")) ){
                        javax.swing.JOptionPane.showMessageDialog(this,"Porfavor llene los datos");
                     }else{
                         javax.swing.JOptionPane.showMessageDialog(this,"El usuario o contraseña utilizados no se encuentran registrados");   
                     }    
                 }
             }
             if (options.getSelectedItem().equals("Vendedora")){
                  if ((Text_USER.getText().equals(vend_user))&&(String.valueOf(CONTRASEÑA.getPassword()).equals(vend_contra)) ){
                     
                     System.out.println("how");
                     
                 }else{
                     
                     if ((Text_USER.getText().equals("Username"))&&(String.valueOf(CONTRASEÑA.getPassword()).equals("*********")) ){
                        javax.swing.JOptionPane.showMessageDialog(this,"Porfavor llene los datos");
                     }else{
                         javax.swing.JOptionPane.showMessageDialog(this,"El usuario o contraseña utilizados no se encuentran registrados");   
                     }    
                 }
             }
             if (options.getSelectedItem().equals("Bodeguero")){
                  if ((Text_USER.getText().equals(bode_user))&&(String.valueOf(CONTRASEÑA.getPassword()).equals(bode_contra)) ){
                     
                     System.out.println("are");
                     
                 }else{
                     
                     if ((Text_USER.getText().equals("Username"))&&(String.valueOf(CONTRASEÑA.getPassword()).equals("*********")) ){
                        javax.swing.JOptionPane.showMessageDialog(this,"Porfavor llene los datos");
                     }else{
                         javax.swing.JOptionPane.showMessageDialog(this,"El usuario o contraseña utilizados no se encuentran registrados");   
                     }    
                 }
             }
              
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Boton_cerrado;
    private javax.swing.JPasswordField CONTRASEÑA;
    private javax.swing.JLabel Contraseña;
    private javax.swing.JPanel LOG;
    private javax.swing.JLabel Nombre1;
    private javax.swing.JLabel Nombre2;
    private javax.swing.JLabel Nombre3;
    private javax.swing.JLabel Nombre_2;
    private javax.swing.JTextField Text_USER;
    private javax.swing.JLabel Usuario1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> options;
    // End of variables declaration//GEN-END:variables
}
